### PR TITLE
Add basic(ms-basic) highlight mode

### PR DESCRIPTION
**Pull request by mkslanc**
*Issue #, if available:* #5550

*Description of changes:*
Add token highlighting and folding for basic language. MS-BASIC was taken as basis, because seems it was the most popular one in times

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Pull Request Checklist:
* [x] No backwards incompatible changes were made to Ace's public interface which is defined through the main typings file (`ace.d.ts`) and its references:
    * https://github.com/ajaxorg/ace/blob/master/ace.d.ts 
    * https://github.com/ajaxorg/ace/blob/master/ace-modes.d.ts 
    * https://github.com/ajaxorg/ace/blob/master/ace-extensions.d.ts

### CODE REVIEW

**Comment by whazor** [comment]
Old school

**Review by whazor — APPROVED** [review]

**Comment by nightwing** [comment]
@whazor should we disable `error  Unexpected trailing comma  comma-dangle` eslint rule? we had added it for old IE, but new browsers all support trailing commas.

**Comment by whazor** [comment]
We don't need to support old IE anymore. However, it would be ironic to disable IE11 support in order to support an even older Microsoft technology.

**Comment by akoreman** [comment]
Could you also add the new modes to [`ace-modes.d.ts`](https://github.com/ajaxorg/ace/blob/master/ace-modes.d.ts) to resolve the failing build

**Pull request merged**
