### PR TITLE
fix newline handling in rtl extension

### LINKED ISSUE #3840: RTL linebreaks
After merging #3658 I have the impression RTL support is almost complete in ACE. Remaining problem: at the moment, pressing enter while on an RTL line incorrectly produces a new LTR line.

Looking at the source, the RTL extension is supposed to prevent that with this function:
https://github.com/ajaxorg/ace/pull/3658/files#diff-39037390fecdb74f84f14bc14e4a5e1dR85
But that function never appears to be called (when I add a debug statement to it, it doesn't appear when I insert a newline on an RTL line). Am I doing something wrong, or is this a bug?

### PR DESCRIPTION
**Pull request by nightwing**
fixes #3840

### CODE REVIEW

**Comment by bartkamphorst** [comment]
@nightwing Would you be able to give an estimated timeline for the next ACE release that includes this fix? Thanks!

**Comment by bartkamphorst** [comment]
Ping @nightwing ; when are you planning a new release (1.4.3) for Ace? We'd love to include this fix for rtl support in [gollum](https://github.com/gollum/gollum/issues/1314)!

**Comment by nightwing** [comment]
Sorry for the  delay. We'll release it in the beginning of the next week.

Btw i have also added rtl option for whole document   too.

**Comment by bartkamphorst** [comment]
Terrific, thank you!

**Pull request merged**
