### PR TITLE
Update Less and CSS modes

### PR DESCRIPTION
**Pull request by matthew-dean**
- Updates property list (supportType) in css_highlight_rules
- Less highlighter updated to inherit CSS support tokens
- Other Less regex borrowed from CSS highlighter
- Sass keywords / control directives removed
- CSS completer added to Less mode

### CODE REVIEW

**Comment by nightwing** [comment]
> Updates property list (supportType) in css_highlight_rules

could you please describe how was it updated (what was added/removed)?

**Comment by matthew-dean** [comment]
@nightwing As far as I could tell, the property list contained numerous CSS properties that were proposed but not finalized. (I had never heard of most of them, and when I looked them up, they were from W3C documents that were marked as going through significant changes, so definitely were not final CSS properties.) Some of the properties were from the earlier spec of flexbox, which was never implemented. (Microsoft only implemented a prefixed version temporarily.) And what the list *didn't* have was the final CSS properties for flexbox.

I didn't go through them one by one; I essentially grabbed a current list of CSS properties from W3Schools and formatted it with pipe separators. That should be fairly comprehensive as far as what's actually used in browsers and, therefore, in style sheets.

**Comment by matthew-dean** [comment]
Maybe that CSS property list isn't comprehensive enough. If you're squidgy about that part, I can revert updating the change to the CSS highlighter. My real goal was to make an up-to-date Less highlighter, which is partially accomplished by having an up-to-date CSS property list.

**Comment by nightwing** [comment]
Updated tests and merged.
Thanks!

**Comment by matthew-dean** [comment]
Yay! My first Ace merge! I'm hoping to add a proper Less completer at some point. I imagine since the Less mode was originally a copy of the SCSS mode with some small modifications that many of the updates I made to Less would apply to SCSS. However, I'm not as familiar with SCSS so I'm not sure I'd be the best person to do it.

Also, I'm planning to make a Classic ASP mode at some point, just because I have an indefinite project that I maintain that's written in it.

**Comment by matthew-dean** [comment]
Uh oh. I just got this error:
```
Cannot read property '0' of undefined
```
in ext_language-tools.js. Here:
```
  prefix: util.retrievePrecedingIdentifier(line, pos.column, results[0] && results[0].identifierRegex),
  matches: matches,
  finished: (--total === 0)
```
It looks like in some circumstances ```results``` is undefined. I assume an issue with the CSS completer + Less tokens?

**Pull request merged**
