### PR TITLE
Update CoffeeScript mode to v2.2.1.

### PR DESCRIPTION
**Pull request by eventualbuddha**
This updates the compiler and the keywords/illegal words. The CoffeeScript compiler update was done like so:

```bash
#!/usr/bin/env bash

if ! which uglifyjs >/dev/null 2>&1; then
    npm install -g uglify-js@3
fi

(
    echo 'define(function(require, exports, module) {'
    echo 'function define(f) { module.exports = f() }; define.amd = {};'
    curl http://coffeescript.org/browser-compiler/coffeescript.js | uglifyjs --comments '/Copyright \d+/'
    echo '});'
) > lib/ace/mode/coffee/coffee.js
```

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Checking in to see if there’s anything I should do to get this looked at. Thanks for your time!

**Comment by nightwing** [comment]
Hi
sorry for the delay, the pull request looks good!
The only i didn't merge it right away is that we are considering moving linters to a separate repository, and i didn't want to update the large file in this repository just before removing it.

**Comment by eventualbuddha** [comment]
Okay, let me know whether there's anything I can do to help!

**Comment by eventualbuddha** [comment]
Checking in again. Any hope here, or should I just close it?

**Pull request merged**
