### PR TITLE
nothing should include dependencies included in ace.js

### PR DESCRIPTION
**Pull request by lukeis**
assume ace is always included

### CODE REVIEW

**Comment by nightwing** [comment]
Could you please describe what this does and why?

**Comment by lukeis** [comment]
This will change the built artifacts to not include transient dependencies (other javascript files) that are already included in the built ace.js file. It reduces duplication of js code that is being included in other files which already exist in ace.js and aren't required, since normal use of ace is to always have the ace.js on the page?

I couldn't think of a case where you wouldn't have ace.js and were trying to use one of the other generated files.

**Comment by nightwing** [comment]
buildSubmodule already has code to exclude files from ace.js https://github.com/ajaxorg/ace/blob/master/Makefile.dryice.js#L328
And i couldn't find any duplicates in built file, where did you see same file included in both places?

**Comment by lukeis** [comment]
this was a few months ago :) (only recently was able to sign the cla...) I'll have to double check and get back to you

**Comment by lukeis** [comment]
so, here's the diff it produces -

https://gist.github.com/lukeis/38cf3c0538f1fb6f91e0b123bea41f6e

Most of which is being removed from the files is included in ace.js (the duplicate content i was seeing), But I just saw a few things that got removed, but shouldn't be. Related to ace/mode/textile*  so, i'll need to revisit this change :)

**Comment by nightwing** [comment]
worker-* files need the duplication since they are loaded into their own webworker where other scripts are not included

**Comment by lukeis** [comment]
yep, correct. Appears this isn't what I thought it was. Thanks for taking a look and talking about it with me!

**Pull request closed without merging**
