### PR TITLE
Add Logtalk language support

### PR DESCRIPTION
**Pull request by pmoura**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pmoura** [comment]
Can a maintainer restart the Travis CI build? It seems to have failed due to some timeout.

**Comment by pmoura** [comment]
Squashed the previous four commits into a single commit for merging.

**Comment by nightwing** [comment]
could you please add a small ~10 line example to the demo/kitchen-sink/docs folder, and resolve the todo comment about the fold rules

**Comment by pmoura** [comment]
Sample file added. The `cstyle` folding does a good job in properly formatted Logtalk source files. But Let me check if we can do it better using custom folding code.

**Comment by pmoura** [comment]
Looked into the `folding` directory. It seems doable to eventually be able to define a folding mode for Logtalk that is better than simply using `cstyle` folding. But it's more complex than I expected and not something that I can do right now. But it's on my TODO list.

**Comment by pmoura** [comment]
I do have the `foldingStartMarker` and `foldingStopMarker` regular expressions from Logtalk folding support I wrote for other text editors (e.g. TextMate):

```javascript
var FoldMode = exports.FoldMode = function(markers) {
    this.foldingStartMarker = /\/\*|:-\s+(?:if|object|protocol|category)(?=[(]))/;
    this.foldingStopMarker = /\*\/|:-\s+(?:endif|end_(object|protocol|category))(?=[.]))/;
};
oop.inherits(FoldMode, BaseFoldMode);
```
The missing logic for the matches is likely easy but I have not found in other fold modes and in the docs a snippet of code that simply uses both markets to return a range of lines for folding.

**Comment by nightwing** [comment]
@pmoura currently we do not have code doing that, though that may be useful for other languages too.

**Pull request merged**
