### PR TITLE
Add folding and behaviours for JSX

### PR DESCRIPTION
**Pull request by mkslanc**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
This does not work for several cases
 - `return <>` should become `return <></>`
 -  `<div>|</div>` enter should indent properly
 - `<div x={>` should insert the closing `}`

**Comment by nightwing** [comment]
@mkslanc i think this should fix the issues with highlighting without adding much complexity, could you please take a look, and add tests for pairing in ``x=`${`; `` and `x=<a href={>`

**Comment by mkslanc** [comment]
> @mkslanc i think this should fix the issues with highlighting without adding much complexity, could you please take a look, and add tests for pairing in `` x=`${`; `` and `x=<a href={>`

Thank you! Sure, will do

**Comment by akoreman** [comment]
Looks pretty good! I played around a bit with it and noticed one weird thing. In the video, the first time I insert `<div>` it doesn't auto-close and only the closing tag gets highlighted. If I do the same thing again below it, it does function as expected. 


https://github.com/ajaxorg/ace/assets/34573235/0ba2a55e-94d3-4e4a-a67d-fdf6ca2aaecf

**Comment by nightwing** [comment]
@akoreman The issue here is that after `}` our tokenizer is unable to distinguish between
```jsx
q=function a(){
}
<div></div>
```
case when `<` is supposed to be treated as less than operator and
```jsx
function a(){
}
<div></div>
```
where it is compiled as jsx tag.

same issue is present for regular expressions too, but since tags are usually not written in that context i am not sure if we need to add extra state for this case.

**Comment by akoreman** [comment]
ah yeah that makes sense, in that case it should only occur in the scenario I used in the video which should not occur in valid JSX/TSX files anyway.

**Review by akoreman — APPROVED** [review]

**Pull request merged**
