### PR TITLE
add Gherkin worker leveraging offical gherkin parser

### PR DESCRIPTION
**Pull request by chmontgomery**
This makes a slight modification to Makefile.dryince.js so that any licenses sitting alongside specific language parsers under lib/ace/mode/<language> are also copied over to the build folder so that licenses stick with the code they apply to. This was necessary because license comment blocks are stripped from files during the build process.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
To the Ace maintainers: Please don't merge this in until the licensing issue described in cucumber/gherkin3#8 has been resolved. Dryice seems to strip the license headers, so a copy of the license would have to be added manually wherever this code ends up (https://github.com/ajaxorg/ace-builds).

**Comment by chmontgomery** [comment]
This makes a slight modification to `Makefile.dryince.js` so that any licenses sitting alongside specific language parsers under `lib/ace/mode/<language>` are also copied over to the build folder so that licenses stick with the code they apply to. This was necessary because license comment blocks are stripped from files during the build process.

**Comment by aslakhellesoy** [comment]
Gherkin3 is going to evolve in its own repo. I'm concerned that a year or two from now the copy of Gherkin3 that lives in Ace is going to be outdated because nobody is making sure it stays uptodate. (The Cucumber team who maintains Gherkin3 certainly won't).

Copying source code between repositories is a practice I'm deeply sceptical about. Not from a licensing perspective, but from a fragmentation perspective.

Wouldn't it be better to create a Gherkin-Ace plugin that:

* Lives in a separate repo
* Depends on Gherkin3 via npm or bower, but doesn't *copy* the source.

**Comment by nightwing** [comment]
I agree, including source code of the few other workers we have now was a mistake, and we do not want to add more external source into ace repository. gherkin_worker.js file can be part of ace but including large linter files for every possible language is not scalable

**Comment by chmontgomery** [comment]
I agree, depending on gherkin3 is MUCH better than copying files.

@nightwing do you have ideas around how we would modify your build script to accommodate for 3rd party parsers? Would you want to pull in dependencies from npm or bower?

Let me know if I should create a separate issue where we can discuss this problem separately.

**Comment by nightwing** [comment]
With both bower and npm users will have to add new rules to their servers and require paths, since the dependencies won't be added to lib/ace folder.
One possible solution is that you could create a separate project ace-gherkin and we could add a hook for linter plugins to register with Ace, something like 
```js
ace.config.registerLinter({path: "path/to/script/loaded/in/webworker"})
```
So people will need to install both ace and ace-gherkin and add the above line to trigger loading of gherkin worker.

**Comment by chmontgomery** [comment]
@nightwing that sounds good to me. I already have a placeholder project for this here: https://github.com/chmontgomery/gherkin-ace

I will have a `build` folder with the parser files ace can consume. I've already had some issues getting the files in the proper amd format so that `dryice` could understand them and properly generate the `worker-gherkin.js` file. What format do you expect this parser to be in? Would a browserify bundle work?

**Comment by nightwing** [comment]
I think anything that exposes one object like
```js
{
    lint: function(doc, cb) {
        // parse doc.getValue() and get annotations
        cb(null, annotations)
    }
};
```

would work

**Pull request closed without merging**
