### PR TITLE
added ziglang support

### PR DESCRIPTION
**Pull request by bajrangCoder**
*Issue #, if available:*
#5428

*Description of changes:*
added the zig mode and syntax higlighting and also a sample example for kitchen sink

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by marinsokol5** [comment]
Hey, thanks a lot for the contribution. 🤗
It looks good overall, I am not too familiar with this language but I tested it a bit in kitchen sink and it looks good. 

The build is currently failing with:
```
/home/runner/work/ace/ace/src/mode/zig_highlight_rules.js
  92:21  error  Parsing error: Invalid regular expression: /\b(?<!\.)-?[\d_]+(?!\.)\b/: Invalid group
```

If we can take a look into that, we can merge it afterwards.

**Comment by bajrangCoder** [comment]
Yeah , soon I will fix it , give some time 

> It looks good overall, I am not too familiar with this 
> language but I tested it a bit in kitchen sink and it looks 
> good.

Yeah I am also not a zig developer 😅, I have written this with the help of `vscode-zig`

**Comment by bajrangCoder** [comment]
Fixed the issue .
Result of `npm run lint`
Screenshot_20240107_190027

**Comment by whazor** [comment]
Hi, could you delete the commented code and delete the `types/index.d.ts`? For the rest it looks good to me.

**Comment by bajrangCoder** [comment]
> Hi, could you delete the commented code and delete the `types/index.d.ts`? For the rest it looks good to me.

Done ✅

**Comment by bajrangCoder** [comment]
I don't have idea about why `npm run cover` fails . I have checked regex and they are working fine(I have tested it on kitchen sink). If anyone have idea about it then tell me, I will try my best to fix it. (@marinsokol5 , @whazor )

**Comment by whazor** [comment]
I also see these errors when opening the mode in the kitchen sink. These are the reported rules that give errors:
```json
[
  {
    "rule": {
      "token": "text",
      "regex": "(\\\\s*)(?=\\\\s*(?:[a-zA-Z_][\\\\w.]*|@\\\\\\".+\\\\\\")?)(\\\\s*)((?:!)?)(\\\\s*)([a-zA-Z_][\\\\w.]*|@\\\\\\".+\\\\\\")",
      "onMatch": null
    },
    "groupCount": 5
  },
  {
    "rule": {
      "token": "text",
      "regex": "(\\\\s*)((?:[a-zA-Z_][\\\\w.]*|@\\\\\\".+\\\\\\")?)((?:!)?)(\\\\s*)(?:([a-zA-Z_][\\\\w.]*|@\\\\\\".+\\\\\\")\\\\b(?!\\\\s*\\\\\\\\())?)",
      "onMatch": null
    },
    "groupCount": 6
  }
]
```

**Comment by bajrangCoder** [comment]
why this error ? due to any wrong regex or anything else?

**Comment by whazor** [comment]
The first rule `(\s*)(?=\s*(?:[a-zA-Z_][\w.]*|@\".+\")?)(\s*)((?:!)?)(\s*)([a-zA-Z_][\w.]*|@\".+\")` has 5 regex groups `( ... )` but you specified 6 classes:
```
"text",
"storage.type.zig",
"text",
"keyword.operator.zig",
"text",
"storage.type.zig"
```

The second rule `(\s*)((?:[a-zA-Z_][\w.]*|@\".+\")?)((?:!)?)(\s*)(?:([a-zA-Z_][\w.]*|@\".+\")\b(?!\s*\\())?)` has 6 regex groups, but you specified 5 classes:
```
"text",
"storage.type.zig",
"keyword.operator.zig",
"text",
"storage.type.zig"
```

The regex is a bit too complicated for me to read, so I cannot see what would be the correct order of classes.

**Comment by bajrangCoder** [comment]
@whazor thanks for pointing out the problem!
Let me try to fix this ...

**Comment by bajrangCoder** [comment]
@whazor still there is problem?

**Comment by whazor** [comment]
LGTM, I think we can ignore code coverage for language modes

**Pull request merged**
