### PR TITLE
Fixes for XML mode

### PR DESCRIPTION
**Pull request by dbrnz**
*Description of changes:*

This takes blank lines into account when positioning the XML locater and fixes the error message when XML tags are mismatched. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dbrnz** [comment]
This is still not quite right... More updates are coming.

**Comment by nightwing** [comment]
let me know if you need help with this.

**Comment by dbrnz** [comment]
Sorry, this has slipped a bit with other commitments -- will aim to get it sorted next week. Thanks.

**Comment by andrewnester** [comment]
@dbrnz are you still interested in finishing this PR? If not, I'll close it

**Pull request closed without merging**
