### PR TITLE
Add a mode for Wollok Programming Language

### PR DESCRIPTION
**Pull request by javierfernandes**
Wollok is OOP language designed for teaching OOP.

https://github.com/uqbar-project/wollok

I've created this PR based on #2696 (https://github.com/ajaxorg/ace/pull/2696) which was merged.

This mode was creating based on the java one, since Wollok lang has a "similar" syntax.

### CODE REVIEW

**Comment by nightwing** [comment]
Sorry for the delay. The pr looks good, could you please fill the  [The Individual CLA](https://docs.google.com/a/c9.io/forms/d/1MfmfrxqD_PNlNsuK0lC2KSelRLxGLGfh_wEcG0ijVvo/viewform) form? See https://github.com/ajaxorg/ace/blob/master/CONTRIBUTING.md for details

**Comment by javierfernandes** [comment]
Cool. I've done before when I submitted the other PR.
Can you please check my username "javierfernandes" Should be there.
Otherwise let me know and I will fill it in again

**Comment by nightwing** [comment]
Sorry, your username is indeed there, i somehow missed it :( need to write a bot to handle this cla stuff

**Comment by nightwing** [comment]
Merged. Thanks!

**Comment by javierfernandes** [comment]
:+1:  !!

**Pull request merged**
