### PR TITLE
fixes #5130: Wrong text color in solarized_dark.css.js (Updated)

### LINKED ISSUE #5130: (Theme): (Solarized Dark uses wrong text color)
### Describe the bug

If you go to the original [solarized web page](https://ethanschoonover.com/solarized/) you can find this blurb:

> Thus in the case of a dark background colorscheme, the normal relationship for background and body text is base03:**base0** (please note that body text is not base00).

base03    #002b36
**base0     #839496**
base00    #657b83
base1     #93a1a1

But solarized_dark.css.js defines the following as the primary text color:

```
.ace-solarized-dark {
  background-color: #002B36;
  color: #93A1A1
}
```

```
.ace-solarized-dark .ace_entity.ace_other.ace_attribute-name,
.ace-solarized-dark .ace_storage {
  color: #93A1A1
}
```
Notice Ace's version uses color, #93A1A1 while the Solarized web page explicitly states the text color should be: #839496

### Expected Behavior

For Solarized Dark, the text color should be: #839496

### Current Behavior

For Solarized Dark, the text color is: #93A1A1.

### Reproduction Steps

Create an Ace Editor using Solarized Dark theming.

### Possible Solution

Change the color value from #93A1A1 to #839496 

### Additional Information/Context

_No response_

### Ace Version / Browser / OS / Keyboard layout

v1.17.0

### PR DESCRIPTION
**Pull request by gurvirbaraich**
Screenshot 2023-04-22 at 2 56 40 PM

### CODE REVIEW

**Comment by InspiredGuy** [comment]
This PR is exactly the same as the previously closed one - https://github.com/ajaxorg/ace/pull/5133, but seems like the issue https://github.com/ajaxorg/ace/issues/5130 mentions one of the changes might be incorrect. Could you please double-check?
P.S. You don't have to re-create a PR in case you need to make some changes, just push another commit to the branch from which you made a PR (in this case `fixed-solarized-dark-theme-text-color-issue-updated`)

**Comment by gurvirbaraich** [comment]
@InspiredGuy, This PR is not same to the closed PR #5133, on the issue https://github.com/ajaxorg/ace/issues/5130#issuecomment-1517854119 doom-goober reclarified the issue and this PR fixes the same.

**Comment by InspiredGuy** [comment]
@gurvirbaraich I see exactly the same diff when I open changed files of both PRs (see screenshots below). maybe I'm missing something, could you please point out what is different between those two?
[this PR](https://github.com/ajaxorg/ace/pull/5137/files):
image
[closed PR](https://github.com/ajaxorg/ace/pull/5133/files):
image

**Comment by gurvirbaraich** [comment]
Let me check. I will update the PR accordingly. Thanks @InspiredGuy

**Pull request closed without merging**
