### PR TITLE
Ext/Searchbox: remove forgotten debugger

### PR DESCRIPTION
**Pull request by gokmen**
it's introduced with in a hotfix PR here https://github.com/ajaxorg/ace/pull/3329

### CODE REVIEW

**Comment by nightwing** [comment]
Thanks!

**Comment by mikeyhew** [comment]
@nightwing will there be a new release coming out soon that includes this PR? The rogue `debugger` statement is causing a [delayed pull request](https://github.com/thlorenz/brace/pull/93) that unfortunately means that the Rust playground ([play.rust-lang.org](https://play.rust-lang.org/)) [doesn't have auto-indentation and closing braces](https://github.com/integer32llc/rust-playground/issues/202). I'm sure it would be possible to work around the issue by forking a few repositories, but it would be simpler for all of us if a new version of Ace were released. Since it's been 3 months since 1.2.8 came out, maybe it's about time for another one? Is there anything I or @shepmaster can do to help get a new release out?

**Comment by nightwing** [comment]
Sorry, i didn't realize that this was blocking brace, and couldn't publish 1.2.9 immediately because it needed some testing and cleanup. The version 1.2.9 released yesterday should be good to be used with brace.

**Comment by shepmaster** [comment]
Thank you for your hard work, @nightwing !

**Comment by mikeyhew** [comment]
Thanks @nightwing!

**Pull request merged**
