### PR TITLE
Proposal: Switch #ace irc channel from freenode.net to libera.chat

### PR DESCRIPTION
**Pull request by zgtm**
*Issue #, if available:*

*Description of changes:*

I just changed the links to the `#ace` IRC channel in the `Readme` and on the "Support" page, as Freenode no longer exists as an IRC network for open source projects.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
@andrewnester I wonder if we should just replace all of these with a link to https://github.com/ajaxorg/ace/discussions.

**Comment by andrewnester** [comment]
Yes, I think we should just replace these links as I don't think the team actively monitors them anymore

**Review by andrewnester — CHANGES_REQUESTED** [review]
Could you please instead replace links to Google Groups and IRC with  http://groups.google.com/group/ace-discuss ?

**Comment by akoreman** [comment]
The links to the IRC channel has been removed from the README (PR #5159) and the website (PR #5118), as such I will go ahead and close this PR.

**Pull request closed without merging**
