### PR TITLE
Create webpack.yml

### PR DESCRIPTION
**Pull request by mitchelfalcon**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Pull Request Checklist:
* [ ] No backwards incompatible changes were made to Ace's public interface which is defined through the main typings file (`ace.d.ts`) and its references:
    * https://github.com/ajaxorg/ace/blob/master/ace.d.ts 
    * https://github.com/ajaxorg/ace/blob/master/ace-modes.d.ts 
    * https://github.com/ajaxorg/ace/blob/master/ace-extensions.d.ts

### CODE REVIEW

**Comment by nlujjawal** [comment]
@h-amirjanyan can you look into reviewing this.

**Comment by nlujjawal** [comment]
Updated the comment.

**Comment by nlujjawal** [comment]
@mitchelfalcon can you please share more context on what improvement will this bring to the Ace?

**Comment by nightwing** [comment]
This seems to be incomplete. Running `npx webpack` in ace directory simply prints an error and exits, so this pull request does not do anything atm.

**Comment by whazor** [comment]
Is this a bot account? this contribution is so weird, there is no information or issue available

**Comment by nightwing** [comment]
@mitchelfalcon closing for now, but please comment if we have misunderstood this pull request.

**Pull request closed without merging**
