### PR TITLE
Add yaml linter

### PR DESCRIPTION
**Pull request by asantos00**
*Description of changes:*
This adds the capacity to lint `yaml` files. I would love to hear your opinion on this, if it makes sense, if it looks correct, and so on.

It also adds a `browserified` version of `yaml-lint` (https://www.npmjs.com/package/yaml-lint) that is needed in `yaml-lint.js`

*Notes*
- Still missing tests (will add them later today)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
Thanks, this looks good, could you also tell which command did you use to create the browserified version?

**Comment by asantos00** [comment]
Hi @nightwing, thank you! I think I've used `browserify yaml-lint.js --outfile yaml-lint.js --standalone lint`. What am I supposed to use? Because I see I'm having some problems on the build 😞

**Comment by rushtehrani** [comment]
Is there a plan to merge this?

**Comment by Ly-lns** [comment]
@nightwing 
Is there a plan to merge this?
I need this feature

**Comment by asantos00** [comment]
I guess I need to do some changes but I'd need help to understand what should I do in order to get a proper browserified version 🤷‍♂

**Comment by huizluo** [comment]
i need this feature

**Comment by andrewnester** [comment]
@asantos00 I think everything is okay with your browserfied version, you can just add it to this file so eslint won't validate it
https://github.com/ajaxorg/ace/blob/master/.eslintignore

**Comment by asantos00** [comment]
@andrewnester sorry, my bad I didn't notice. I've added that to eslintignore, let me know if you need any other changes (also I need your approval for the workflows to run)

**Review by andrewnester — APPROVED** [review]

**Comment by andrewnester** [comment]
Merged! Thanks a lot for your contribution

**Pull request merged**
