### PR TITLE
Added check for 'undefined' on for-in

### PR DESCRIPTION
**Pull request by rwrife**
Added check for 'undefined' on for-in to prevent Internet Explorer 11 (and older) from crashing.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
I do not see this issue on ie 11.
Does this happen because internet explorer or does something on your page add a property to object prototype?

**Comment by rwrife** [comment]
Yeah looking at this test code:

var t = {1:"one",2:"two",3:"three"}; for(x in t) { console.log(t[x].toLowerCase()); }

...it does appear to work, so your theory about someone adding a prototype to the object is probably true.

**Comment by nightwing** [comment]
Did you find another solution for this?

**Comment by rwrife** [comment]
Yes, your theory was correct and a method was being added to Object.prototype, removing this fixed the for-in loop issue.

**Pull request closed without merging**
