### PR TITLE
Add more detailed class names to the selection marker

### PR DESCRIPTION
**Pull request by xixixao**
This allows for more styling of the selection marker (think rounded box).

### CODE REVIEW

**Comment by nightwing** [comment]
This still doesn't allow to have rounded corners on selection marker similar to sublime text.
Would you still need this classes if support for rounded corners was added with something like
https://github.com/ajaxorg/ace/commit/b64e1f258a59aec9e0d42e7314a90d0eb0355ad6?

**Comment by xixixao** [comment]
If you can make an outline of the selection with it then that's what I was going for (I haven't tested the commit).

**Comment by nightwing** [comment]
I think b64e1f2 cannot help to draw outline but this one can't be used for that either. Could you show what css you want to use to make an outline?

I know only 3 ways to get proper outline on selection:
`.ace_marker-layer {  -webkit-filter: drop-shadow(0 0 1px #fff); }`, [svg](http://www.webodf.org/demo/ci/wodotexteditor-0.5.6/localeditor.html) and [canvas/webgl](
http://code.tests.onejs.io/)

**Comment by xixixao** [comment]
That is true. What I have right now is a broken "box" - I give top and left border to the start line, left border to the middle ones and left and bottom border to the last one - wouldn't actually look that bad if the top line didn't extend all the way to the end (same as sublime, that's not hard to do). But you are right that it won't be perfect. Let me rethink how I want to do this now that I know I can't get a proper outline.

**Comment by nightwing** [comment]
closing until further updates

**Pull request closed without merging**
