### PR TITLE
improve bash highlight rules

### PR DESCRIPTION
**Pull request by nightwing**
@lennartcl this adds highlighting for `$()` and `${}`
also changes color of `"$var"` to be the same as color of unquoted variable `$var` though i am not entirely sure if it's a good idea or not

see https://rawgit.com/ajaxorg/ace/bash/kitchen-sink.html

fixes https://github.com/ajaxorg/ace/issues/2674

### CODE REVIEW

**Comment by lennartcl** [comment]
I like the quoted "$var" getting colors too.

- [ ] One thing I notice here is that with "$foo" only the foo is getting colored now ($ is black), while things like "$?" are fully getting colored. I'm not sure if that's intentional?

Note that I posted another (minor) issue related to variable highlighting at https://github.com/ajaxorg/ace/issues/2709.

**Comment by nightwing** [comment]
added highlighting for declare and readonly 
I've used different tokens for `$` and variable name to make things like `"$foo$bar"` more readable, but it doesn't look good in all themes, should i change it back to emit one token?

**Comment by lennartcl** [comment]
@nightwing I see. For me it's just very much part of the variable or expression, so I would prefer it to have the same color.

**Comment by nightwing** [comment]
Ok, reverted that change.

**Pull request merged**
