### PR TITLE
vim support gq

### PR DESCRIPTION
**Pull request by nightwing**
partial improvement for https://github.com/ajaxorg/ace/issues/2865

can be tested on https://raw.githack.com/ajaxorg/ace/vim-hardwrap/kitchen-sink.html

with `:set tw=20`  `gq}`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by psvenk — COMMENTED** [review]
Thank you for this pull request and for Ace generally. I just played with this, and it seems to work quite well; I would love to see this merged because it would make working in Overleaf much easier (together with [disabling soft wrapping](https://github.com/overleaf/web/issues/223#issuecomment-824362238)).

Here are some things that I noticed:
1. In Vim, both `gqq` and `gqgq` wrap the current line, but only `gqgq` is implemented here; pressing `gqq` acts like `q` and starts recording a macro on the next keystroke.
2. When two lines have a combined length less than the maximum width, pressing `gqgq` on the first line acts like `J` rather than `gq$`, whereas in Vim (as far as I can tell) `gqgq`, `gqq`, and `gq$` are synonyms.

**Review by ilya-babanov — COMMENTED** [review]
I see that we have tests for soft wrap, can we add some for hard wrap too?

**Comment by nightwing** [comment]
Thanks. i've added tests and fixed support for gqq.

**Comment by psvenk** [comment]
Thank you!

**Pull request merged**
