### PR TITLE
Add Nord theme (https://www.nordtheme.com/)

### PR DESCRIPTION
**Pull request by lmn8**
*Issue #, if available:* https://github.com/ajaxorg/ace/issues/4202

*Description of changes:* Make the popular Nord theme available to Ace.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
There are two issues with the theme: selection and active line colors are same, so it is not possible to see single line selections, comments are not visible over selection.

**Comment by lmn8** [comment]
Fixed. Should be okay to merge now

**Comment by nightwing** [comment]
I found we had a workaround for themes that set same color to selection and highlight, could you please check if after my changes theme looks correct, or if we should make some other changes?

**Comment by lmn8** [comment]
Made gutter color match Sublime, LGTM :shipit:

**Comment by nightwing** [comment]
Thanks!

**Pull request merged**
