### PR TITLE
New auto-generated API Reference document

### PR DESCRIPTION
**Pull request by mkslanc**
*Issue #, if available:*

*Description of changes:*

- Changed link to lead to new API reference document

[Repo for Ace documentation generator](https://github.com/mkslanc/ace-docs/tree/master) 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by andrewnester** [comment]
I like new documentation a lot! I guess the best way for us to proceed would be to setup a GitHub Action which would automatically build this doc and put it on https://ace.c9.io/ace-docs for example.

I it something that you could work on? @mkslanc

**Comment by mkslanc** [comment]
> I like new documentation a lot! I guess the best way for us to proceed would be to setup a GitHub Action which would automatically build this doc and put it on https://ace.c9.io/ace-docs for example.
> 
> I it something that you could work on? @mkslanc

I set up simple deploying action for that, but with more complex DevOps stuff, i think, @nightwing is better man for that job

**Comment by nightwing** [comment]
can be tested on https://nightwing.github.io/ace/
When this branch is ready, we can change the gh-pages branch in settings of this repo to publish change to ace.c9.io

**Review by andrewnester — APPROVED** [review]

**Comment by andrewnester** [comment]
Looks good!

**Pull request merged**
