### PR TITLE
Preliminary support for theme and mode data-attributes

### PR DESCRIPTION
**Pull request by houli**
Implements #2711 
Uses data-attributes to configure the theme and mode of the editor element. I've chosen to use the simple `data-theme="monokai"` over `data-theme="ace/theme/monokai"` because as far as I can tell all themes live in `ace/theme/`. Do let me know if this doesn't make sense.

### CODE REVIEW

**Comment by houli** [comment]
Any thoughts on this?

**Comment by nightwing** [comment]
Allowing to set options via dataset might be useful, but we shouldn't use hardcoded list of options in ace.js.

We could have an api like
```js
ace.edit(domNode, [options])
new Editor(renderer, [options])
new EditSession(value, [options])
```

With that `ace.edit` could do

```js
if (!options) options = domNode.dataSet
```

and editor would simply call `this.setOptions(options)`

One problem with the api above is that it makes harder to pass non option parameters to the constructors (e.g. session in https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L72), but maybe just ignoring unknown options would be enough.

cc @lennartcl

**Comment by houli** [comment]
I think the best place to start with this is to decide upon an exhaustive list of all the possible options. I'm not too familiar with all of the options available so that would be appreciated @nightwing

**Comment by nightwing** [comment]
Exhaustive list of options is at https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L2612, setOptions already handles that

**Comment by houli** [comment]
Hi @nightwing, we've made some more comprehensive changes to this API including the programmatic options object on the ace.edit function.

**Comment by vanillajonathan** [comment]
Bootstrap 5 now prefix their data attributed with `bs-` which seems like a good idea. Ace could do the same and prefix theirs with `ace-`, example `data-ace-theme="monokai"`.
> Data attributes for all JavaScript plugins are now namespaced to help distinguish Bootstrap functionality from third parties and your own code. For example, we use `data-bs-toggle` instead of `data-toggle`.
https://getbootstrap.com/docs/5.1/migration/#javascript

**Pull request closed without merging**
