### PR TITLE
Tokenizer without mask for issue #2632

### PR DESCRIPTION
**Pull request by pthurlow**
Here is an implementation that replaces the bit mask with an array of character indexes to be highlighted.  It requires minimal code change but does increase the memory footprint of all completion matches

### CODE REVIEW

**Comment by pthurlow** [comment]
This pull request fixes #2632

**Comment by nightwing** [comment]
Increasing used memory is rather bad, and indexOf should have almost same performance as not caching the result at al. Maybe we should use several bitmasks?

**Comment by pthurlow** [comment]
Yea good point,  multiple masks would alleviate the problem.  I would suggest also not allowing highlighting past the maximum allowable index of the mask to avoid the wrap around issue.  Its possible that just not supporting highlighting over a certain character count is good enough for most use cases.

**Comment by nightwing** [comment]
Fixed the issue in #3730 by storing indexes of places where filtertext needs to be splitted.

**Pull request closed without merging**
