### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by nightwing** [comment]
why is this needed?

**Comment by paladox** [comment]
Well it's not but shoulden this be built against 0.10 instead of the really old 0.6 version.

**Comment by paladox** [comment]
And we also test against 0.10 in travis. So 0.10 works.

**Comment by nightwing** [comment]
But 0.6 here is the minimal version not the preferred one, and static-highlight server still works with 0.6

**Pull request closed without merging**
