### PR TITLE
Live autocomplete delay

### PR DESCRIPTION
**Pull request by rnconrad**
Added delay and threshold editor-wide settings for making the live
autocomplete popup less erratic when typing short words quickly in large
files. Uses `lang.delayedCall` for timing, suppresses calls to
`doLiveAutocomplete` until the popup is allowed to be shown.

Use alongside normal editor options:

```
editor.setOptions({
            enableLiveAutocompletion: true,
            liveAutocompletionDelay: 100,
            liveAutocompletionThreshold: 3
        });
```

Also added an extension (.s) to `modelist`, which is fairly trivial, but can be separated/changed as needed.

### CODE REVIEW

**Comment by luminaxster** [comment]
Will love to have this feature on master.

**Comment by jechlin** [comment]
+1, essential feature for master. Please merge...?

**Comment by aapetrov** [comment]
+1, could you please merge it?

**Comment by leolorenzoluis** [comment]
Why hasnt this been merged yet?

**Comment by its-poole** [comment]
Any updates on this? debouce would be quite handy, I believe.

**Comment by xizi-xu** [comment]
Any update on this please?

**Comment by mikecargal** [comment]
+1 on this.  Code completion can be expensive, much more so if you have to do it several times as a user types characters quickly.  We really need for the typing to pause to decide to pay for code completion.

Any update on when this might appear?

**Comment by CherryPetale** [comment]
please...

**Comment by akoreman** [comment]
This was added as part of #5177, closing this PR.

**Pull request closed without merging**
