### PR TITLE
Fix issues found by lgtm

### PR DESCRIPTION
**Pull request by xiemaisi**
This fixes a few minor JavaScript issues found by [lgtm](https://lgtm.com); for more details see https://lgtm.com/projects/g/ajaxorg/ace.

Each commit fixes one particular kind of issue; let me know if you'd prefer a different organisation.

(Full disclosure: I work on lgtm's JavaScript analysis.)

### CODE REVIEW

**Comment by nightwing** [comment]
Thanks. Lgtm is awesome!
Is `Useless conditional` conditional rule new? i don't remember it from last time i have tried lgtm.

**Comment by xiemaisi** [comment]
Thanks, @nightwing! We've had "Useless conditional" for a while, but we recently made it a bit smarter.

Would you perhaps consider taking another look at our [PR integration](https://lgtm.com/docs/lgtm/using-lgtm-analysis-continuous-integration)? We've made many performance and stability improvements since you last tried it, and several large projects such as [AMP HTML](https://github.com/ampproject/amphtml) and [three.js](https://github.com/mrdoob/three.js) have been using it for a while now without problems.

**Comment by nightwing** [comment]
@xiemaisi when i try to reenable the integration i end up in  a redirect loop on https://github.com/login/oauth/authorize, saying 

> Reauthorization required
> This application has made an unusually high number of requests to access your account. Please reauthorize the application to continue.

**Comment by xiemaisi** [comment]
Ah, sorry to hear that. I'm told it should be fixed now; can you try again?

**Pull request merged**
