### PR TITLE
(Theme): (Solarized Dark uses wrong text color) #5130

### PR DESCRIPTION
**Pull request by ratulSharker**
*Issue #5130:*
- #5130 

*Description of changes:*
- changed the solarized theme primary color from `#93A1A1` to `#839496`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by marinsokol5** [comment]
It's a slightly lower contract ratio but acceptable at 4.7

**Comment by marinsokol5** [comment]
But yeah looks good indeed according to the docs.

**Comment by marinsokol5** [comment]
Thanks for the contribution!

**Comment by ratulSharker** [comment]
Hi @marinsokol5,

Thanks for prompt response and review. I am new to ace community. Can you please explain about what do you meant in contract ratio ?

I did not understand the comment:

> It's a slightly lower contract ratio but acceptable at 4.7

**Pull request merged**
