### PR TITLE
Add QML language support

### LINKED ISSUE #3809: Add QML file format syntax highlightning
http://doc.qt.io/qt-5/qtqml-syntax-basics.html
https://highlightjs.org/static/demo/ -- look for QML

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

Fix #3809

### CODE REVIEW

**Comment by patrickelectric** [comment]
Can someone point why it's failing and how can I fix it ? I'm not a web developer guy.

**Comment by patrickelectric** [comment]
fixed

**Comment by patrickelectric** [comment]
Ping @nightwing

**Comment by nightwing** [comment]
@patrickelectric this looks good, Thank you! Could you please add the cla statement from https://github.com/ajaxorg/ace/blob/master/.github/PULL_REQUEST_TEMPLATE.md in a comment so that we can merge the pull request?

**Comment by patrickelectric** [comment]
Fix Issue #3809

Description of changes: Add initial QML support 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Comment by patrickelectric** [comment]
@nightwing is that enough ?

**Comment by nightwing** [comment]
Thank you!

**Pull request merged**
