### PR TITLE
Updated list of strict/reserved Rust keywords

### PR DESCRIPTION
**Pull request by Enamex**
As of 4-Jul-2015. Used [this](https://doc.rust-lang.org/src/syntax/parse/token.rs.html#545-599).

### CODE REVIEW

**Comment by nightwing** [comment]
regexps in strings are a bit hard to read
could you please check if https://github.com/ajaxorg/ace/tree/highlight/rust highlights all rust operators correctly

**Comment by Enamex** [comment]
That link points to the root directory of the repo.

The operators-in-regex sometimes build and sometimes not! It's very weird but I can't download and test locally :/

**Comment by nightwing** [comment]
Link to the commit is at the top of file list https://github.com/ajaxorg/ace/commit/3bbc7d75d672eef19f4e64c68a908e1716841164#diff-6e75d9c1f4e549bcdc128975b582889cL96

you can try it online at https://rawgit.com/ajaxorg/ace/highlight/rust/kitchen-sink.html

the build fail here is caused by `|\^`.
Since there is only one `\`, in regex it ends up as `|^` and matches start of the line.

**Comment by Enamex** [comment]
I changed:
`regex: /-->?|--?|\+\+?|==?|<>|<<=|>>=|[<>]=?|[&]{2}|[|]{2}|[|!$&^*\-+%/]=?/ },`
to:  `regex: /->|--?|\+\+?|==?|<|>|<<=|>>=|[&]{2}|[|]{2}|[$]|[|!&^*\-+%/]=?/ },`

Wasn't sure what `<>` was matching except literally `<>` (for empty generics list). Also, there's no `<>=` or `-->` in Rust.

I might be misunderstanding the regex, though.

**Comment by bluss** [comment]
Don't give up @Enamex, we need to improve this. It's a bit embarrassing to have this out of date in our default rust live environment which uses Ace :smile:

**Comment by Enamex** [comment]
Hmm...
[Build status](https://travis-ci.org/Enamex/ace/builds/69905353), [src](https://github.com/Enamex/ace/blob/Enamex-patch-1/lib/ace/mode/).

Audit :D ?

**Comment by nightwing** [comment]
`[<>]=?` would match `<` or `>` or `<=` or `>=`

I've updated regex in highlight/rust branch to
```js
regex: /--?|\+\+?|==?|<<=|>>=|&{2}|\|{2}|[<|>!$&^*\-+%/]=?/
```

It is based on this branch and passes tests so if highlighting in https://rawgit.com/ajaxorg/ace/highlight/rust/kitchen-sink.html looks good  i'll merge it now

**Comment by Enamex** [comment]
Right. Just add `->` and `=>` and it's good to go.

**Comment by nightwing** [comment]
Thank you

**Pull request merged**
