### PR TITLE
Fix for issue 3041

### PR DESCRIPTION
**Pull request by wajnberg**
Signed-off-by: Moshe Wajnberg wajnberg@il.ibm.com

### CODE REVIEW

**Comment by nightwing** [comment]
this can't be merged because it doesn't handle selection and cursor position

**Comment by tomerm** [comment]
@nightwing this is just a prototype aiming at illustrating the feature described in #3041 . If overall there is an agreement on the feature request, we will submit full implementation in this ticket.

**Comment by wajnberg** [comment]
Can you please elaborate on handle selection and cursor position ? Did you see any particular problems with this in RTL text direction ?

Thank you

**Comment by nightwing** [comment]
@wajnberg with this patch in rtl mode cursor is still positioned as if the text was ltr.
@tomerm bidi and rtl support is a long requested [feature](https://github.com/ajaxorg/ace/issues/1429), so help in implementing it, is much appreciated.

**Comment by nightwing** [comment]
i think this is superceded by https://github.com/ajaxorg/ace/pull/3400, please let me know if you think more changes are still needed.

**Pull request closed without merging**
