### PR TITLE
[mode-mysql] Fix autocomplete typo: “groupby_concat” → “group_concat”

### PR DESCRIPTION
**Pull request by shaunlebron**
## Description

This PR corrects a typo in the autocompletion keyword `groupby_concat` for MySQL mode.

It should be [`group_concat`](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat) instead:

CleanShot 2023-06-06 at 14 31 24@2x

## Affected users

Some metabase users have noted this autocompletion typo:
* https://github.com/metabase/metabase/issues/30144
* https://stackoverflow.com/questions/71855564/grouby-concat-metabase-mysql

### CODE REVIEW

**Review by InspiredGuy — APPROVED** [review]

**Comment by akoreman** [comment]
Thanks for your contribution.

**Comment by shaunlebron** [comment]
Thank you!  Will `v1.22.1` be rolled soon?

**Comment by akoreman** [comment]
We don't have a set release schedule for Ace but I'll do a release this week.

**Comment by akoreman** [comment]
Ace 1.22.1 has been released.

**Pull request merged**
