### PR TITLE
added gruvbox theme

### PR DESCRIPTION
**Pull request by Rasarts**

### CODE REVIEW

**Comment by nightwing** [comment]
Looks good. Merged.

**Comment by Rasarts** [comment]
Cool. Thanks.

**Comment by nightwing** [comment]
@Rasarts could you please sign a cla for this commit? See the link in https://github.com/ajaxorg/ace/blob/master/CONTRIBUTING.md

**Comment by nightwing** [comment]
@Rasarts had to revert this due to missing CLA in https://github.com/ajaxorg/ace/pull/2985, sorry

**Pull request merged**
