### PR TITLE
Add mode for Gobstones language

### PR DESCRIPTION
**Pull request by javierfernandes**
Gobstones is an imperative programming language designed for introductory subjects teaching programming.

http://www.gobstones.org/

### CODE REVIEW

**Comment by javierfernandes** [comment]
I'm not sure why travis build failed. All test passed fine

**Comment by nightwing** [comment]
test failed because of trailing comma at https://github.com/javierfernandes/ace/blob/add-mode-for-gobstones/lib/ace/mode/gobstones_highlight_rules.js#L33
see https://travis-ci.org/ajaxorg/ace/builds/92546174#L207

**Comment by javierfernandes** [comment]
Cool ! Thanks ! 
It is now fixed !

**Comment by nightwing** [comment]
Could you add the example document, which you used to generate the test file?

**Comment by javierfernandes** [comment]
Ok. Done. I've added
* demo/kitchen-sink/docs/gobstones.gbs
* lib/ace/mode/_test/text_gobstones.txt

Regards

**Comment by nightwing** [comment]
Thanks merged

**Comment by javierfernandes** [comment]
Many thanks !! :)

**Comment by javierfernandes** [comment]
Hey @nightwing any chance you can also take a look at #2776 ?
I've done something preety similar to this PR but for that other language (wollok)

Thanks dude !

**Pull request merged**
