### PR TITLE
Added Alda Music programming language support

### LINKED ISSUE #4215: Add Alda Music Language support
Would be nice to have a packaged editor support this. Haven't seen any so far. Reusing the tmLanguage file from the project here: https://github.com/abhi18av/Alda-VsCode/tree/master/syntaxes

### PR DESCRIPTION
**Pull request by JesseChua94**
Added a proper example for the demo

*Issue #, if available:*
Fix #4215

*Description of changes:*
Added support for the Alda Music programming language using the TMLanguage Tool and a TMLanguage file from https://github.com/abhi18av/Alda-VsCode/tree/master/syntaxes. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nightwing** [comment]
@JesseChua94 not using es2018 features is intentional since we still support some old browsers, and regexp lookbehinds are sadly not implemented in firefox and safari https://caniuse.com/#search=regex

Usually it is easy to modify rules to not require lookbehind by either adding a new rule that matches the lookbehind pattern or adding a new state. 

Alternatively if you only case about chrome, you can add eslint comment to enable es2018 features in the highlight rules file

**Comment by JesseChua94** [comment]
> @JesseChua94 not using es2018 features is intentional since we still support some old browsers, and regexp lookbehinds are sadly not implemented in firefox and safari https://caniuse.com/#search=regex
> 
> Usually it is easy to modify rules to not require lookbehind by either adding a new rule that matches the lookbehind pattern or adding a new state.
> 
> Alternatively if you only case about chrome, you can add eslint comment to enable es2018 features in the highlight rules file

Okay that makes sense. I figured I'd ask just in case. It is clear now how to adapt it without lookbehinds after looking at the docs again. Thanks!

**Comment by JesseChua94** [comment]
Hi @nightwing! Will this work?

**Comment by nightwing** [comment]
Thank you!

**Pull request merged**
